name: CI

on:
  push:
    branches:
      - main
      - release/*
  pull_request:
    branches:
      - main
      - release/*


jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: php-actions/composer@v5

    - name: Install Modules
      run: npm install

    - name: Lint JavaScript
      run: npm run lint

    - name: Lint PHP
      run: composer run-script lint

    - name: Unit Tests
      run: npm run test
